name: Testing yakyak

on: push

jobs:
  test-yakyak:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v1
      with:
        node-version: '12'
    - run: npm install -g coffee-script
    - run: npm ci
    - run: npm test
