name: Testing yakyak

on: push

jobs:
  test_node:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v1
      with:
        node-version: '12'
    - run: npm install -g coffee-script
    - run: npm ci
    - run: npm test
    - run: |
        export YAKYAK_VERSION=`node -e "console.log(require('./package.json').version);"`
        # debug information for the electron packager
        export DEBUG=electron-packager
        echo $DEBUG
        echo $YAKYAK_VERSION

        sudo dpkg --add-architecture i386
        sudo apt-get -qq update
        sudo rm /var/lib/dpkg/lock
        sudo apt-get install -y -qq wine-stable zip xvfb fakeroot
        wine wineboot --init # WINEARCH=win32
        #
        # actuall building of the binaries
        npm run -loglevel ${NPM_DEBUG_LEVEL} deploy:linux-x64
