name: Build yakyak binaries

on: push

jobs:
  build_binaries:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v1
      with:
        node-version: '12'
    - run: npm install -g coffee-script
    - run: npm ci
    - run: |
        export NPM_DEBUG_LEVEL=silent
        export YAKYAK_VERSION=`node -e "console.log(require('./package.json').version);"`
        # debug information for the electron packager
        export DEBUG=electron-packager
        echo $DEBUG
        echo $YAKYAK_VERSION

        sudo dpkg --add-architecture i386
        sudo apt-get -qq update
        sudo rm /var/lib/dpkg/lock
        sudo apt-get install -y -qq wine-stable zip xvfb fakeroot
        wine wineboot --init # WINEARCH=win32
        #
        # actuall building of the binaries
        npm run -loglevel ${NPM_DEBUG_LEVEL} deploy:linux-x64
        npm run -loglevel ${NPM_DEBUG_LEVEL} deploy:linux-arm64
        npm run -loglevel ${NPM_DEBUG_LEVEL} deploy:linux-ia32
        npm run -loglevel ${NPM_DEBUG_LEVEL} deploy:darwin-x64
        npm run -loglevel ${NPM_DEBUG_LEVEL} deploy:darwin-arm64
        xvfb-run npm run -loglevel ${NPM_DEBUG_LEVEL} deploy:win32
        #
        # RPM and DEB binaries
        # install fpm
        gem install --no-document fpm
        # needed to deploy on rpm / pacman
        sudo apt-get install -y -qq rpm libarchive-tools
        #
        npm run -loglevel ${NPM_DEBUG_LEVEL} gulp deploy:linux-x64:rpm:nodep
        npm run -loglevel ${NPM_DEBUG_LEVEL} gulp deploy:linux-x64:deb:nodep
        npm run -loglevel ${NPM_DEBUG_LEVEL} gulp deploy:linux-x64:pacman:nodep
        npm run -loglevel ${NPM_DEBUG_LEVEL} gulp deploy:linux-ia32:rpm:nodep
        npm run -loglevel ${NPM_DEBUG_LEVEL} gulp deploy:linux-ia32:deb:nodep
        npm run -loglevel ${NPM_DEBUG_LEVEL} gulp deploy:linux-ia32:pacman:nodep
